# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  commit:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Runs a single command using the runners shell
    - name: correction commit
      run: cat spots.json | sed -e 's/_storage_options": "{\\"color\\":\\"\([a-zA-Z]*\)\\",\\"opacity\\":\\"\([0-9]\)\\"}/_storage_options": {\n          "color": "\1",\n          "opacity": "\2"\n        }/gi' | sed -e 's/_umap_options": "{\\"color\\":\\"\([a-zA-Z]*\)\\",\\"opacity\\":\\"\([0-9]\)\\"}/_umap_options": {\n          "color": "\1",\n          "opacity": "\2"\n        }/gi' > ./spots_sed.json
      
